esphome:
  name: sniffer

esp32:
  variant: esp32s3
  framework:
    type: arduino

# Geen logger, geen extra vlaggen. Puur de UART-logica.
uart:
  - id: quatt_sniffer
    rx_pin: GPIO18
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1
    debug:
      direction: RX
      dummy_receiver: true
      after:
        timeout: 50ms
      sequence:
        - lambda: |-
            if (bytes.size() >= 4) {
               // De modbus-logica is hier nu uitgeschakeld om elke CPU-overhead te elimineren.
            }
